### ISSUE TITLE
部分问题

### ISSUE THREAD

**Issue by incasedo** [DictPedia/ZhuyinPinyin#1]
shànɡ
ɡè

转换都为空

**Comment by terrylinooo** [comment]
好久沒看 github。沒想到有人會用。我今天測試一下修改後再更新。謝謝回報。

**Comment by terrylinooo** [comment]
經過測試，您提供的字元 g 看起來像是英文字母 g，但實際上是 unicode 字符，不是真正的英文字母 g，所以會出錯。

對於來源出處的轉換您必須自行 str_replace 所有可能的字符到 a-z 才不會出錯。

```
echo $zh->decodePinyin('shàng') . "\n"; 

echo $zh->decodePinyin('gè') . "\n";
```
